backend:
  name: git-gateway
  use_large_media_transforms_in_media_library: false
  branch: master
  commit_messages:
    uploadMedia: Upload “{{path}}” [skip ci]
    deleteMedia: Delete “{{path}}” [skip ci]

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  # - name: "music"
  #   label: "Featured Music"
  #   title: "{{slug}}"
  #   folder: "_music"
  #   summary: "{{title}} by {{person}}"
  #   create: true
  #   slug: "{{slug}}"
  #   fields:
  #     - { label: "A Unique Title", name: "title", widget: "string" }
  #     - { label: "Length (mm:ss)", name: "length", widget: "string" }
  #     - {
  #         label: "Type of Content",
  #         name: "type",
  #         widget: "select",
  #         options: ["Set", "Playlist"],
  #       }
  #     - {
  #         label: "Created/Streamed at",
  #         name: "date",
  #         widget: "datetime",
  #         date_format: "DD.MM.YYYY",
  #         time_format: "HH:mm",
  #       }
  #     - { label: "URL link", name: "link", widget: "string" }
  #     - { label: "Played/Curated by", name: "person", widget: "string" }

  - name: "events"
    label: "Events"
    label_singular: "Event"
    title: "{{slug}}"
    folder: "_events"
    create: false
    slug: "{{slug}}"
    summary: "{{title}} - {{start}}"
    fields:
      - label: "Event Banner"
        name: "banner"
        widget: "image"
        media_library:
          config:
            max_file_size: 512000
      - { label: "Event Title", name: "title", widget: "string" }
      - {
          label: "Event Start",
          name: "start",
          widget: "datetime",
          date_format: "DD.MM.YYYY",
          time_format: "HH:mm",
          format: "LLLL",
        }
      - {
          label: "Event End",
          name: "end",
          widget: "datetime",
          date_format: "DD.MM.YYYY",
          time_format: "HH:mm",
          format: "LLLL",
        }
      - { label: "Event Address", name: "address", widget: "string" }
      - { label: "Ticket Price", name: "price", widget: "number" }
      - { label: "Event Capacity", name: "capacity", widget: "number" }
      - {
          label: "Presale only",
          name: "presale_only",
          widget: "boolean",
          default: false,
        }
      - label: "Lineup"
        name: "lineup"
        widget: "list"
        fields:
          - { label: "Artist Name", name: "name", widget: "string" }
          - { label: "Country Abbreviation", name: "country", widget: "string" }
          - {
              label: "Artist's Label(s)",
              name: "label",
              widget: "string",
              required: false,
            }
          - {
              label: "Artist's SoundCloud/Spotify page",
              name: "link",
              widget: "string",
              required: false,
            }
      - { label: "Event Text", name: "body", widget: "markdown" }
      # - label: "Featured Music"
      #   name: "music_list"
      #   widget: "list"
      #   fields:
      #     - label: "Linked Music Piece"
      #       name: "music"
      #       widget: "relatedMusic"
      #       collection: "music"
      #       display_fields: ["{{title}} by {{person}}"]
      #       search_fields: ["title", "person"]
      #       value_field: "title"

  - name: "terms"
    label: "Terms and Conditions"
    identifier_field: name
    summary: "Our Terms and Conditions"
    folder: "_pages"
    create: false
    fields:
      - { label: "The terms", name: "content", widget: "markdown" }

  - name: "email"
    label: "Confirmation Email"
    identifier_field: name
    summary: "Upcoming event confirmation email"
    folder: "_email"
    create: false
    fields:
      - { label: "Email Text", name: "body", widget: "markdown" }
